#!/usr/bin/env perl

use strict;

sub usage {
    print STDERR "Usage: $0 offset < WARC_or_ARC_FILE | gzip -dc | less -S\n";
    print STDERR "       $0 offset < WARC_or_ARC_FILE | gzip -dc | od -c | less -S\n";
    exit 1;
}

usage() unless (defined $ARGV[0]);
my $offset=$ARGV[0];

seek (STDIN, $offset, 0);

print while(<STDIN>);

