#!/usr/bin/env python

# -------------------------------------------------------------------  #
# Copyright (c) 2007-2008 Hanzo Archives Limited.                      #
#                                                                      #
# Licensed under the Apache License, Version 2.0 (the "License");      #
# you may not use this file except in compliance with the License.     #
# You may obtain a copy of the License at                              #
#                                                                      #
#     http://www.apache.org/licenses/LICENSE-2.0                       #
#                                                                      #
# Unless required by applicable law or agreed to in writing, software  #
# distributed under the License is distributed on an "AS IS" BASIS,    #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or      #
# implied.                                                             #
# See the License for the specific language governing permissions and  #
# limitations under the License.                                       #
#                                                                      #
# You may find more information about Hanzo Archives at                #
#                                                                      #
#     http://www.hanzoarchives.com/                                    #
#                                                                      #
# You may find more information about the WARC Tools project at        #
#                                                                      #
#     http://code.google.com/p/warc-tools/                             #
# -------------------------------------------------------------------  #


from optparse import OptionParser 
import browser
from index import Index 



def main():                      
    usage = """usage: %prog location  
    
        allow the user to browse WARC files from the given location
"""
    parser = OptionParser(usage)    
    parser.add_option("-p","--port",
                                action="store",dest="portnum" , default=False,
                                help="port number on which to host webserver")       
    parser.add_option("-R","--recurse",
                                action="store_true",dest="recurse" , default=False,
                                help="search subdirectories for warc files")                                   
    parser.add_option("-v","--verbose",
                                action="store_true",dest="verbose" , default=False,
                                help="print more information")                               
    (options , args) = parser.parse_args()
    if len( args ) < 1:
         parser.error( "Please provide a location to browse WARC files from")
    location = args[0]
    idx = Index( location , options.recurse  )
    
    
    browser.browse( idx )


if __name__ == "__main__":
    main()
