.\"
.TH warcvalidator " 09/01/2008 "
.nh
.ad l
.SH "NAME"
warcvalidator \-    checks WARC file consistency.

.SH "SYNOPSIS"
.HP 3
\fBwarcvalidator\fR   \fB-f \fIfile.warc [-v] [-t \fIworking_dir\fP]
.SH "DESCRIPTION"
.PP
\fBwarcvalidator\fR
checks if all WARC files in a directory are valid or not. It calls the warcvalidator
command described previously for each WARC file in the directory.


.SH "OPTIONS"
.PP
The options for the command. 
\fBwarcvalidator\fR
are\ :

.PP
\fB\-f\fR 
.RS 4
This option is mandatory when you use warcvalidator. It is used to indicate the name of the WARC file
to validate.

.RE
.PP
\fB\-t\fR 
.RS 4
This option is optional, it is as described previously.
.RE
.PP
\fB\-v\fR 
.RS 4
This option is different from -v options given previously, in this case it allows to display a result
message.

.SH "EXAMPLES"
.TP
users@users-desktop:~$ warcvalidator -f file.warc -v
.RE
.PP
.RS 5
Use the warcvalidator command.

